server:
  port: 9997

spring:
  profiles:
    active: dev
  application:
    name: jdbc-achieve
  datasource:
    url: jdbc:mysql://kon:3306/test?allowMultiQueries=true&characterEncoding=utf8&useUnicode=true&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    jdbc:
      repositories:
        enabled: true
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
    lazy-loading-enabled: false